# ----------------------------------------------------------------
# LISTENER
# ----------------------------------------------------------------
listener 1883 0.0.0.0

# ----------------------------------------------------------------
# AUTHENTICATION
# allow anonymous connections — this is a honeypot
# attackers can connect without credentials
# ----------------------------------------------------------------
allow_anonymous true

# ----------------------------------------------------------------
# LOGGING
# remove defualt log, use mqtt_logger.py
# ----------------------------------------------------------------
log_dest none

# log the client ID and IP of every connection
connection_messages true
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S

# ----------------------------------------------------------------
# PERSISTENCE
# save messages to disk so we don't lose data on restart
# ----------------------------------------------------------------
persistence true
persistence_location /var/lib/mosquitto/
